CREATE TABLE barber (
    barber_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    barber_name TEXT NOT NULL,
    barber_location TEXT NOT NULL,
    services INTEGER REFERENCES services(services_id),
    phone_number TEXT,
    email TEXT
);