CREATE TABLE barber_services (
    barber_services_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    barber_id INTEGER REFERENCES services(services_id),
    services_id INTEGER REFERENCES barber(barber_id)
);